# Generated by Django 5.0.1 on 2024-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='First_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='musician',
            name='Last_Name',
            field=models.CharField(max_length=15),
        ),
    ]
